version:  '3.6'
volumes:
  db:
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_USER: cminor
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: cminor
      MYSQL_PASSWORD: secret
    volumes:
      - db:/var/lib/mysql
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql